### ISSUE TITLE
Contribution.md

### ISSUE THREAD

**Issue by axecopfire** [AugustaDevs/Resources#1]
We need a guide for new contributors.
It should be named `contribution.md`

**Comment by locemarn** [comment]
can i take this one?

**Comment by osmarpetry** [comment]
@axecopfire  What do you expect from this file? Just "How to do a fork then a PR" (then I can help) or "Best code practices and what should do with your code"?

**Comment by axecopfire** [comment]
@osmarpetry I think in the doc there could be:
- how to add a resource using markdown
- a code of conduct
- how to do a fork would be good.
